# This file contains all resources present in the system when Cleaner is processed
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: php-apache
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: php-apache
  namespace: default
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
        - name: php-apache
          image: php:8.0-apache
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: not-backed-by-autoscaler
  namespace: default
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
        - name: php-apache
          image: php:8.0-apache
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi