{{- if and .Values.web.enabled .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "k8s-cleaner.fullname" . }}-web
  labels:
    {{- include "k8s-cleaner.labels" . | nindent 4 }}
  {{- with .Values.web.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.web.ingress.className }}
  ingressClassName: {{ .Values.web.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.web.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "k8s-cleaner.fullname" . }}-web
                port:
                  number: {{ .Values.web.port }}
  {{- with .Values.web.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
