apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unused
  namespace: bar
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi   