apiVersion: apps.projectsveltos.io/v1alpha1
kind: Cleaner
metadata:
  name: completed-pods
spec:
  schedule: "*/5 * * * *"
  resourcePolicySet:
    resourceSelectors:
    - kind: Pod
      group: ""
      version: v1
      excludeDeleted: false
      evaluate: |
        function evaluate()
          hs = {}
          hs.matching = false

          -- Check if the pod has a deletionTimestamp field (i.e., pod is terminating)
          if obj.metadata.deletionTimestamp ~= nil then
            -- If deletionTimestamp has a value, the pod is terminating
            hs.matching = true
          end

          return hs
        end
  action: Scan